# Econometrics seminar

### Wooldridge
We are going to need data sets from wooldridge. [Click here](https://pypi.org/project/wooldridge/) for installation instructions

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import wooldridge

In [ ]:
wooldridge.data()

  J.M. Wooldridge (2019) Introductory Econometrics: A Modern Approach,
  Cengage Learning, 7th edition.

  401k       401ksubs    admnrev       affairs     airfare
  alcohol    apple       approval      athlet1     athlet2
  attend     audit       barium        beauty      benefits
  beveridge  big9salary  bwght         bwght2      campus
  card       catholic    cement        census2000  ceosal1
  ceosal2    charity     consump       corn        countymurders
  cps78_85   cps91       crime1        crime2      crime3
  crime4     discrim     driving       earns       econmath
  elem94_95  engin       expendshares  ezanders    ezunem
  fair       fertil1     fertil2       fertil3     fish
  fringe     gpa1        gpa2          gpa3        happiness
  hprice1    hprice2     hprice3       hseinv      htv
  infmrt     injury      intdef        intqrt      inven
  jtrain     jtrain2     jtrain3       jtrain98    kielmc
  labsup     lawsch85    loanapp       lowbrth     mathpnl
  meap00_01  meap01      meap93        meapsingle  minwage
  mlb1       mroz        murder        nbasal      ncaa_rpi
  nyse       okun        openness      pension     phillips
  pntsprd    prminwge     prison        rdchem      rdtelec
  recid      rental      return        saving      school93_98
  sleep75    slp75_81    smoke         traffic1    traffic2
  twoyear    volat       vote1         vote2       voucher
  wage1      wage2       wagepan       wageprc     wine

1. The data in 401K.RAW are a subset of data analyzed by Papke (1995) to study the relationship between participation in a 401(k) pension plan and the generosity of the plan. The variable *prate* is the percentage of eligible workers with an active account; this is the variable we would like to explain. The measure of generosity is the plan match rate, *mrate*. This variable gives the average amount the firm contributes to each worker’s plan for each 100¢ contribution by the worker. For example, if mrate = 0.50, then a 100¢ contribution by the worker is matched by a 50¢  contribution by the firm.
    1. Find the average participation rate and the average match rate in the sample of plans.
    2. Now, estimate the simple regression equation $prate = \beta_0 + \beta_1*mrate$, and report the results along with the sample size and R-squared.
    3. Interpret the intercept in your equation. Interpret the coefficient on mrate.
    4. Find the predicted prate when mrate = 3.5. Is this a reasonable prediction? Explain what is happening here.
    5. How much of the variation in prate is explained by mrate? Is this a lot in your opinion?

<p id="average"><b>1</b></p>
The data in 401K.RAW

In [ ]:
wooldridge.data('401k', description=True)

name of dataset: 401k
no of variables: 8
no of observations: 1534

+----------+---------------------------------+
| variable | label                           |
+----------+---------------------------------+
| prate    | participation rate, percent     |
| mrate    | 401k plan match rate            |
| totpart  | total 401k participants         |
| totelg   | total eligible for 401k plan    |
| age      | age of 401k plan                |
| totemp   | total number of firm employees  |
| sole     | = 1 if 401k is firm's sole plan |
| ltotemp  | log of totemp                   |
+----------+---------------------------------+

L.E. Papke (1995), “Participation in and Contributions to 401(k)
Pension Plans:Evidence from Plan Data,” Journal of Human Resources 30,
311-325. Professor Papke kindly provided these data. She gathered them
from the Internal Revenue Service’s Form 5500 tapes.

In [ ]:
df = wooldridge.data('401k')
df

           prate  mrate  totpart  totelg  age  totemp  sole   ltotemp
0      26.100000   0.21   1653.0  6322.0    8  8709.0     0  9.072112
1     100.000000   1.42    262.0   262.0    6   315.0     1  5.752573
2      97.599998   0.91    166.0   170.0   10   275.0     1  5.616771
3     100.000000   0.42    257.0   257.0    7   500.0     0  6.214608
4      82.500000   0.53    591.0   716.0   28   933.0     1  6.838405
...          ...    ...      ...     ...  ...     ...   ...       ...
1529   85.099998   0.33    553.0   650.0   24   907.0     0  6.810143
1530  100.000000   2.52    142.0   142.0   17   197.0     1  5.283204
1531  100.000000   2.27   1928.0  1928.0   35  2171.0     0  7.682943
1532  100.000000   0.58    166.0   166.0    8   931.0     1  6.836259
1533  100.000000   0.45   2179.0  2179.0   24  3187.0     0  8.066835

[1534 rows x 8 columns]

<p id="average"><b>1.A</b></p>
Find the average participation rate and the average match rate in the sample of plans.

In [ ]:
print(f'The average participation rate is {df.prate.mean().round(3)}')

The average participation rate is 87.363

In [ ]:
print(f'The average match rate is {df.mrate.mean().round(3)}')

The average match rate is 0.732

<p id="average"><b>1.B</b></p>
Now, estimate the simple regression equation $$\widehat{prate} =\widehat{ \beta_0} + \widehat{ \beta_1}mrate ,$$ and report the results along with the sample size and $R$-squared.

In [ ]:
import statsmodels.formula.api as smf
mod = smf.ols(formula='prate ~ mrate', data=df)
res = mod.fit()
print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  prate   R-squared:                       0.075
Model:                            OLS   Adj. R-squared:                  0.074
Method:                 Least Squares   F-statistic:                     123.7
Date:                Tue, 22 Sep 2026   Prob (F-statistic):           1.10e-27
Time:                        14:44:23   Log-Likelihood:                -6437.0
No. Observations:                1534   AIC:                         1.288e+04
Df Residuals:                    1532   BIC:                         1.289e+04
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     83.0755      0.563    147.484      0.000      81.971      84.180
mrate          5.8611      0.527     11.121      0.000       4.827       6.895
==============================================================================
Omnibus:                      394.767   Durbin-Watson:                   1.908
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              870.172
Skew:                          -1.444   Prob(JB):                    1.11e-189
Kurtosis:                       5.296   Cond. No.                         2.32
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

<p id="average"><b>1.C</b></p>
Interpret the intercept in your equation. Interpret the coefficient on mrate.

<p id="average"><b>1.D</b></p>
Find the predicted *prate* when $mrate = 3.5$. Is this a reasonable prediction?
Explain what is happening here.

In [ ]:
res.predict(df.loc[df['mrate']==3.5])

730    103.589233
dtype: float64

<p id="average"><b>1.E</b></p>
How much of the variation in prate is explained by mrate? Is this a lot in your opinion?

In [ ]:
print(f'The variation in prate is explained by mrate {res.rsquared.round(3)}')

The variation in prate is explained by mrate 0.075

1. The data set in CEOSAL2.RAW contains information on chief executive officers for U.S. corporations. The variable salary is annual compensation, in thousands of dollars, and ceoten is prior number of years as company CEO.
    1. Find the average salary and the average tenure in the sample.
    2. How many CEOs are in their first year as CEO (that is, ceoten = 0)? What is the longest tenure as a CEO?
    3. Estimate the simple regression model $$\log(salary) =  \beta_0 + \beta_1 ceoten + u,$$ and report your results in the usual form. What is the (approximate) predicted percentage increase in salary given one more year as a CEO?

In [ ]:
wooldridge.data('ceosal2', description=True )

name of dataset: ceosal2
no of variables: 15
no of observations: 177

+----------+--------------------------------+
| variable | label                          |
+----------+--------------------------------+
| salary   | 1990 compensation, $1000s      |
| age      | in years                       |
| college  | =1 if attended college         |
| grad     | =1 if attended graduate school |
| comten   | years with company             |
| ceoten   | years as ceo with company      |
| sales    | 1990 firm sales, millions      |
| profits  | 1990 profits, millions         |
| mktval   | market value, end 1990, mills. |
| lsalary  | log(salary)                    |
| lsales   | log(sales)                     |
| lmktval  | log(mktval)                    |
| comtensq | comten^2                       |
| ceotensq | ceoten^2                       |
| profmarg | profits as % of sales          |
+----------+--------------------------------+

See CEOSAL1.RAW

In [ ]:
df = wooldridge.data('ceosal2')
df

,salary,age,college,grad,comten,ceoten,sales,profits,mktval,lsalary,lsales,lmktval,comtensq,ceotensq,profmarg
0,1161,49,1,1,9,2,6200.0,966,23200.0,7.057037,8.732305,10.051908,81,4,15.580646
1,600,43,1,1,10,10,283.0,48,1100.0,6.396930,5.645447,7.003066,100,100,16.961130
2,379,51,1,1,9,3,169.0,40,1100.0,5.937536,5.129899,7.003066,81,9,23.668638
3,651,55,1,0,22,22,1100.0,-54,1000.0,6.478509,7.003066,6.907755,484,484,-4.909091
4,497,44,1,1,8,6,351.0,28,387.0,6.208590,5.860786,5.958425,64,36,7.977208
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,264,63,1,0,42,3,334.0,43,480.0,5.575949,5.811141,6.173786,1764,9,12.874251
173,185,58,1,0,39,1,766.0,49,560.0,5.220356,6.641182,6.327937,1521,1,6.396867
174,387,71,1,1,32,13,432.0,28,477.0,5.958425,6.068426,6.167517,1024,169,6.481482
175,2220,63,1,1,18,18,277.0,-80,540.0,7.705263,5.624018,6.291569,324,324,-28.880867
176,445,69,1,0,23,0,249.0,31,828.0,6.098074,5.517453,6.719013,529,0,12.449800

<p id="average"><b>1.A</b></p>
Find the average salary and the average tenure in the sample.

In [ ]:
print(f' The average salary is { df.salary.mean().round(3)}')

 The average salary is 865.864

In [ ]:
print(f' The average tenure is { df.ceoten.mean().round(3)}')

 The average tenure is 7.955

<p id="average"><b>1.B</b></p>
How many CEOs are in their first year as CEO (that is, $ceoten=0$)? What is the longest tenure as a CEO?

In [ ]:
print(f"There are {len(df.loc[df['ceoten']==0])} CEOs in their first year as CEO ")

There are 5 CEOs in their first year as CEO

In [ ]:
print(f"Longest tenure as a CEO is {df['ceoten'].max()}")

Longest tenure as a CEO is 37

<p id="average"><b>1.C</b></p>

Estimate the simple regression model $$\log(salary) =  \beta_0 + \beta_1 ceoten + u,$$ and report your results in the usual form. What is the (approximate) predicted percentage increase in salary given one more year as a CEO?

In [ ]:
import statsmodels.formula.api as smf
mod = smf.ols(formula='np.log(salary)~ceoten', data=df)
res = mod.fit()

In [ ]:
print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         np.log(salary)   R-squared:                       0.013
Model:                            OLS   Adj. R-squared:                  0.008
Method:                 Least Squares   F-statistic:                     2.334
Date:                Tue, 22 Sep 2026   Prob (F-statistic):              0.128
Time:                        14:52:01   Log-Likelihood:                -160.84
No. Observations:                 177   AIC:                             325.7
Df Residuals:                     175   BIC:                             332.0
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      6.5055      0.068     95.682      0.000       6.371       6.640
ceoten         0.0097      0.006      1.528      0.128      -0.003       0.022
==============================================================================
Omnibus:                        3.858   Durbin-Watson:                   2.084
Prob(Omnibus):                  0.145   Jarque-Bera (JB):                3.907
Skew:                          -0.189   Prob(JB):                        0.142
Kurtosis:                       3.622   Cond. No.                         16.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

# C3, C4, C5, C6, C7- HW

C8

8. [To complete](#complete) this exercise you need a software package that allows you to generate data from the uniform and normal distributions.
    1. Start by generating 500 observations $x_i$ – the explanatory variable – from the [uniform](#uniform) distribution with range [0,10]. (Most statistical packages have a command for the Uniform[0,1] distribution; just multiply those observations by 10.) What are the sample mean and sample standard deviation of the $x_i$?
    2. Randomly generate $500$ [errors](#errors), $u_i$, from the Normal[0,36] distribution. (If you generate a Normal[0,1], as is commonly available, simply multiply the outcomes by six.) Is the sample average of the $u_i$ exactly zero? Why or why not? What is the sample standard deviation of the $u_i$?
    3. Now generate the $y_i$ as $$y_i = 1+2x_i + u_i = \beta_0 + \beta_1x_i + u_i;$$ that is, the population intercept is one and the population slope is two. Use the data to run the [regression](#regression) of $y_i$ on $x_i$. What are your estimates of the intercept and slope? Are they equal to the population values in the above equation? Explain.
    4. Obtain the OLS residuals, $\hat{u}_i$, and verify that equation (2.60) hold (subject to rounding error).
    5. Compute the same [quantities](#quantities) in equation $$\sum\limits_{i=1}^n \hat{u}_i = 0, \sum\limits_{i=1}^n x_i\hat{u}_i = 0  $$ but use the errors $u_i$ in place of the residuals. Now what do you conclude?

<p id="complete"><b>8.</b></p>
8. To complete this exercise you need a software package that allows you to generate data from the uniform and normal distributions.

In [ ]:
import random

<p id="uniform"><b>8.A</b></p>

Start by generating 500 observations $x_i$ – the explanatory variable – from the uniform distribution with range [0,10]. (Most statistical packages have a command for the Uniform[0,1] distribution; just multiply those observations by 10.) What are the sample mean and sample standard deviation of the $x_i$?

In [ ]:
X = np.array([random.uniform(0, 10) for _ in range(500)])
print(f'500 observations is \n {X}')

500 observations is
 [5.55905418e+00 9.64995572e+00 6.97756101e+00 5.19590396e+00
 4.13411675e+00 3.63420858e+00 9.22280194e+00 9.40508271e+00
 3.27193422e-01 9.05008852e+00 4.35892270e+00 9.57024788e+00
 3.58346407e+00 7.60987512e+00 7.37947833e+00 6.97869337e+00
 2.49669641e+00 1.80937526e+00 5.56292091e+00 1.86540811e+00
 7.57180970e-01 4.28650096e+00 9.36917952e+00 8.57754632e+00
 5.59162865e-01 2.19285036e+00 3.77817648e+00 5.03117189e+00
 2.80211592e+00 1.33843553e+00 6.20600843e+00 5.27888041e+00
 1.05341318e+00 3.37377813e-01 1.21711951e+00 4.08806294e+00
 1.15156662e+00 9.11072052e+00 4.68683108e+00 1.32364173e+00
 7.53157396e-01 4.09541860e+00 7.50270865e+00 9.45123124e+00
 4.58191135e+00 3.56333629e+00 6.20620964e+00 8.50113143e+00
 4.95067392e+00 9.92544309e+00 2.94544782e+00 7.10919230e-02
 4.69756912e+00 5.67262627e+00 6.23052756e+00 5.97070246e+00
 4.81246010e+00 9.45202433e+00 2.04006955e+00 7.76868650e+00
 3.40228532e+00 5.48120288e-01 4.55405262e+00 2.25338663e+00
 7.63603403e+00 3.87170294e+00 8.24495162e+00 3.73895080e-01
 5.52984091e+00 9.14987068e+00 3.18977564e+00 8.74686727e+00
 3.72033443e+00 4.09762407e-01 2.34373734e+00 1.08169706e+00
 6.93802282e+00 3.58909435e+00 5.57237745e+00 4.00045053e+00
 7.69333993e+00 6.26109740e+00 4.01900489e+00 3.37137164e+00
 2.27512714e+00 2.07696396e+00 9.21672586e+00 4.93187659e+00
 1.63212079e+00 3.53881421e+00 8.66498388e+00 1.65071298e-02
 3.85614716e+00 2.46422315e+00 4.65337445e+00 2.50220305e+00
 4.87664798e+00 7.22380262e+00 3.23382018e+00 6.07254857e+00
 4.65995616e+00 1.29499491e+00 1.17346395e+00 6.17516509e+00
 6.76233076e+00 8.34129945e+00 3.70340177e+00 4.40720437e+00
 2.28420549e+00 2.60365817e+00 2.87705743e+00 6.31630497e+00
 5.62699918e+00 4.31850328e+00 3.58055750e+00 2.53974536e+00
 4.05540813e+00 1.39376690e+00 6.49426494e+00 7.00055013e+00
 3.68615241e+00 3.49628424e+00 6.14128681e+00 5.16443036e+00
 4.10232635e+00 1.41509851e+00 6.75572472e+00 8.93507206e+00
 9.22044167e+00 2.93354989e+00 2.06535226e+00 2.95372910e+00
 6.53684907e+00 3.77885123e+00 5.98118268e+00 4.49613115e+00
 1.51727166e+00 8.12800155e+00 1.96282608e+00 1.27704519e+00
 7.53337127e+00 9.75858377e+00 5.33098671e+00 3.98572141e+00
 3.54516008e+00 5.35169056e+00 1.15394637e+00 5.69212210e-01
 5.92865306e+00 2.60827136e+00 1.09384999e+00 3.87803755e+00
 7.75500846e+00 2.16750575e-01 6.46239730e+00 6.30013782e+00
 9.18003419e+00 2.09342163e-01 9.73680342e+00 6.07231760e-01
 3.04300862e+00 1.01497754e+00 7.82114286e-01 9.83962939e+00
 5.64358875e-01 8.49694960e-01 4.24861877e+00 6.53335798e+00
 2.84441796e+00 6.90883261e+00 7.90544506e+00 5.87571331e+00
 7.25085302e+00 5.55758061e+00 2.37316395e+00 2.47590778e+00
 7.72900684e+00 7.61131451e+00 1.90028997e+00 6.54949899e+00
 5.30771419e+00 4.01169076e+00 2.26479026e+00 5.19741769e+00
 8.42638596e+00 3.66328051e+00 1.69964769e+00 2.04113641e+00
 7.38635415e+00 6.40123201e+00 9.63706460e+00 1.61096446e+00
 4.50807140e+00 1.75266909e+00 9.19705629e+00 9.88129094e+00
 9.16668432e+00 7.54613063e+00 7.77758753e+00 2.70313894e+00
 5.31330587e+00 3.64378646e+00 9.76793316e-03 3.18878040e-01
 4.59519459e+00 6.71297870e+00 5.86071778e+00 2.75393845e+00
 4.54103901e+00 8.32828233e+00 5.01024745e+00 8.38798631e+00
 2.48694656e+00 6.06441969e+00 1.74263625e+00 8.23864852e-01
 7.33086494e+00 2.93458425e+00 1.21899543e+00 5.96100601e+00
 4.78796762e+00 1.09594695e-01 2.07046013e+00 8.98349455e-01
 9.10543222e+00 4.92398770e+00 3.85822765e+00 2.35314183e+00
 6.25940895e+00 5.18273447e+00 8.48384337e+00 3.78662140e+00
 6.53195794e-01 9.54838563e+00 6.12694835e-01 2.74586106e+00
 1.43019111e+00 7.93441735e+00 8.61897659e+00 6.62384319e-01
 8.08297739e+00 1.26212172e+00 1.59647372e+00 7.63966713e+00
 3.58685179e+00 4.81854122e+00 4.40025877e+00 9.58296166e+00
 7.03029586e-01 9.87135640e-01 2.70597429e+00 9.45910334e+00
 5.99086451e+00 4.81596841e+00 6.63892953e+00 5.27440415e+00
 9.18707540e+00 8.95151481e+00 4.00483706e+00 9.75949273e-01
 2.14441936e+00 8.72035094e+00 3.15031580e+00 6.15172700e+00
 2.69806176e+00 5.96495072e+00 7.03106470e+00 4.37647853e-01
 7.42527594e+00 5.60498677e+00 2.51786831e+00 6.44167556e+00
 6.53736554e+00 4.25262835e+00 2.24186123e+00 5.80317923e+00
 3.15100678e+00 8.75002848e+00 7.90336412e+00 3.39918688e+00
 5.22442849e+00 6.96012288e+00 6.37496918e+00 6.44986284e+00
 9.09048464e+00 3.43720322e+00 5.36998317e+00 8.40093369e+00
 9.26296829e+00 1.23207006e+00 1.71464315e-01 2.54540602e-01
 2.03517509e+00 7.67029391e+00 1.83652109e-01 9.84626768e+00
 2.24411156e+00 6.77967173e+00 3.47009132e+00 2.03950469e+00
 7.62017956e+00 9.13504482e+00 6.20835296e+00 8.91544308e+00
 4.78034052e+00 6.64717844e+00 9.09533872e+00 1.86729075e+00
 6.59984861e+00 9.61419862e+00 3.18914515e+00 5.42700114e+00
 4.66459521e+00 4.30744107e+00 2.02245598e+00 7.71061171e-01
 7.65848294e+00 6.74256216e+00 2.90646358e+00 7.97798226e+00
 4.49197384e+00 1.72140286e+00 7.70233507e+00 1.16589868e+00
 2.90499624e+00 6.00826540e+00 3.68983703e+00 8.30187466e-02
 6.21825306e+00 1.58317244e+00 2.03168407e+00 6.09526775e+00
 2.26969936e-01 9.51188979e+00 8.41355348e+00 9.12179527e+00
 2.96615994e+00 2.93689675e+00 7.06860101e+00 9.16353934e+00
 1.94178216e+00 6.45742422e+00 6.96777975e+00 8.97077585e+00
 1.43376240e+00 3.04200194e+00 1.74356930e+00 7.12905258e-01
 9.90798908e+00 8.86003308e+00 3.95497213e+00 6.57781737e+00
 8.40234589e+00 1.15900129e+00 8.60543110e-02 1.83598860e+00
 6.32380493e+00 9.89893986e+00 6.14247403e+00 7.65686565e+00
 8.77512582e+00 3.83491617e-02 2.09843169e+00 9.75481096e+00
 7.79081000e+00 3.68465059e-01 3.87777912e+00 3.93058284e+00
 1.64769221e+00 1.69011179e+00 7.07932809e+00 4.98787327e+00
 2.74183687e+00 6.85937557e+00 9.11131464e+00 9.40266190e-01
 9.64533750e+00 2.29147108e+00 1.05648715e+00 2.20235209e+00
 6.50357895e+00 8.65667757e+00 2.62538417e+00 9.32113875e+00
 7.87948915e+00 2.31054395e+00 7.62940268e+00 2.73170415e+00
 7.13352820e+00 4.59724494e+00 4.24297935e+00 2.02953832e+00
 5.82262334e+00 2.57592820e+00 2.81468433e+00 8.17021271e+00
 5.44047594e+00 7.42187113e+00 7.46474911e+00 9.08484478e+00
 3.59646034e+00 9.45485940e+00 9.04829636e+00 1.58607312e+00
 9.60950774e+00 4.79504501e+00 1.68243528e+00 9.66600888e+00
 3.42669786e+00 2.54497285e+00 6.62413972e+00 4.39706065e+00
 4.78008563e+00 4.50142135e+00 5.42835143e+00 5.74791078e+00
 6.69034247e+00 2.87783215e-01 9.65582525e+00 9.04562717e+00
 5.57212056e+00 5.27991942e+00 2.07229365e-01 3.26849813e-01
 4.74056322e+00 9.00211181e+00 4.78397105e+00 4.90418601e+00
 7.39154830e-01 6.37015432e+00 7.55446855e+00 7.91666837e+00
 3.41454100e+00 7.81617858e+00 3.83457947e+00 1.31432745e+00
 5.49328619e+00 8.80012193e+00 1.28974503e+00 2.07431402e+00
 8.02282099e+00 1.63019088e+00 5.52273644e+00 2.37517089e+00
 7.53948587e+00 5.38113163e+00 8.18075001e+00 3.70932952e+00
 6.43300200e+00 8.51773398e+00 1.91319692e+00 3.31460137e+00
 7.14828286e+00 6.20703646e+00 6.90667630e+00 9.00134192e+00
 4.14824690e+00 9.83966288e+00 1.31324186e+00 5.69765733e+00
 8.42458100e+00 3.25856364e+00 3.55235325e-02 3.79412583e+00
 3.54115577e+00 3.08269423e+00 9.40131342e+00 1.28373530e+00
 6.84245386e+00 7.41886812e+00 4.62574864e+00 3.50948502e+00
 3.02794184e+00 7.27798262e+00 9.81823079e+00 3.89917395e-01
 7.27292864e+00 8.37071841e+00 6.96848439e+00 2.32438193e+00
 1.93944777e+00 8.17810655e+00 2.12975635e+00 6.42630580e+00
 1.39439492e+00 9.37077418e+00 5.66968301e+00 8.25381833e+00
 8.85610450e+00 2.33728503e+00 4.33916227e+00 1.94663506e-01
 4.97593254e+00 5.17122005e+00 2.87638825e+00 6.32653003e+00
 4.27423855e+00 6.48905846e+00 4.56705372e+00 6.13493681e+00]

In [ ]:
print(f"Sample mean of X is {X.mean().round(3)}")

Sample mean of X is 4.871

In [ ]:
print(f"Sample standard deviation of X is {X.std(ddof=1).round(3)}")

Sample standard deviation of X is 2.856

<p id="errors"><b>8.B</b></p>
2. Randomly generate $500$ errors, $u_i$, from the Normal[0,36] distribution. (If you generate a Normal[0,1], as is commonly available, simply multiply the outcomes by six.) Is the sample average of the $u_i$ exactly zero? Why or why not? What is the sample standard deviation of the $u_i$?

In [ ]:
mean = 0 # mean from normal distribution
mu = 6 # standard deviation of normal distribution
U = np.array([random.normalvariate(mean,mu) for _ in  range(0,500)])
print(f'500 errors is \n {U}')

500 errors is
 [-4.30022584e+00 -2.44699367e+00  4.03731353e+00 -8.42789794e+00
 -8.69653355e+00 -4.88586603e-01 -4.40164195e+00  5.65033663e+00
 -8.72952731e+00  1.29643437e+00 -5.97693705e+00 -1.47801254e+00
 -3.60556152e+00 -3.66146000e+00  8.13038151e+00  2.51079455e+00
 -1.20864965e+00 -1.96890186e+00  2.26839704e+00  3.61728983e+00
 -8.78338510e+00  3.00645909e+00 -4.91777925e+00  6.01448266e-01
 -6.67299252e+00 -5.97469363e+00  1.78257448e+00 -7.44983703e+00
  2.97510583e+00 -1.46069319e+00  2.12969210e+00  2.06203850e+00
 -7.69718393e+00 -7.87158169e+00 -6.17361399e+00  6.91741095e+00
 -1.02500793e+01  9.30823785e+00  2.59765179e+00 -5.48358298e+00
 -5.59768017e-01 -1.56371459e+00  6.52690152e-01  8.20545357e-01
 -7.07939694e+00  1.23278382e+00 -2.52162269e+00 -1.05289282e+01
 -6.69327725e+00  9.19295007e+00 -1.03970303e+00 -9.84296457e+00
  7.02638907e+00  6.04123933e+00 -4.37718102e+00  4.53790354e+00
  1.51916945e+00  2.75538324e-01 -6.14674198e-01  3.55412433e+00
  3.39943628e+00 -3.69958531e+00 -1.91084516e+00 -1.12603739e+00
 -2.99570760e-01 -4.51656529e+00  1.24585742e+00 -2.24742881e+00
  6.30999983e-01  1.65716346e+00 -5.93974276e+00  8.68133717e-01
 -1.09983503e+01 -5.76660659e+00  3.46838281e+00  2.89286511e+00
 -1.64694908e+00 -8.88242963e+00  2.45359034e+00 -7.61924194e+00
 -3.62650283e+00  2.79543385e+00  2.72658862e+00 -1.01168883e+01
 -9.30743225e+00 -1.36406707e+00 -2.47120730e+00  6.67224881e+00
 -6.86126209e+00  5.43435914e+00 -4.94216709e-01 -5.18186372e+00
  3.33434376e+00 -5.24006647e+00 -2.25766993e+00 -4.92284184e+00
  1.04694539e+00 -8.71439546e+00  7.67104970e+00 -1.33918637e+00
  4.52406220e+00 -9.27861008e+00 -7.09299471e+00 -1.94727517e-01
  1.77711952e+00 -1.27817503e+01 -1.27260274e+01  7.14408679e+00
  2.07825218e+00  9.03388275e+00 -7.65687915e+00  8.24168793e+00
 -1.08795993e+01  8.78139039e+00  1.46461070e+01 -7.27936970e-01
  2.89838235e+00  7.04067316e-01  1.70184647e+00  8.04693506e-01
  5.24045208e+00 -2.30403558e+00  3.29304777e+00 -2.87310250e+00
 -3.04119414e+00 -6.32678891e+00 -1.24986510e+00  1.01449135e+01
 -9.79732589e+00 -5.22059193e+00  1.40710324e+01 -1.06806736e+01
 -1.66063444e+01 -2.63523953e+00 -1.54584240e+01 -2.83894606e+00
 -3.72803222e-02  3.93974583e+00  3.89274699e+00  7.51750793e+00
  4.52760524e+00 -3.28496188e+00 -5.69382763e+00 -2.90257397e+00
  4.46573306e+00  6.86141909e+00  4.74055334e+00  7.25532987e+00
  4.20087712e+00 -2.74353297e+00  2.32873829e+00 -1.42384801e+01
 -8.93874890e+00 -3.51143149e-01  1.10088651e+01 -1.00126762e+01
  4.91959954e+00 -1.21437971e+00  8.17012511e+00 -1.31079208e+01
 -6.45499357e+00  2.03560594e+00  4.33767853e-01  7.28697899e+00
  7.55496004e+00 -6.13215462e+00 -1.51644529e+00  1.72365736e-01
  3.77607527e+00 -2.37325340e+00 -7.46146954e+00 -2.80907239e+00
 -4.71586367e-01  4.79712191e+00  2.13805869e+00  5.46003044e+00
  7.58804995e+00  1.53567112e+00 -1.67735915e-01  6.39358012e+00
 -6.34488398e-01  3.73315748e+00 -3.77906319e+00  1.97055064e+00
 -2.06518736e+00 -5.95560184e+00 -7.87147938e+00  1.55685399e+01
  9.56223022e+00 -5.69687690e+00 -3.17867643e+00 -6.16577866e+00
 -2.38330987e+00  6.27625514e+00 -2.78860741e-01  1.05754594e+00
 -6.81177781e+00  4.34148139e+00 -6.14340599e-01 -6.03162396e+00
 -5.52229494e+00 -3.24203490e+00 -4.29649664e+00 -4.18258590e+00
 -3.90570351e+00  1.49409926e+00 -5.60087877e-01 -1.28757934e+01
  1.76769727e+00  5.29527862e+00  4.74514886e+00  1.95326994e+00
 -2.52512063e+00 -6.20897985e-01 -8.10496313e+00  1.91196260e+00
  3.31118160e+00 -3.07515980e+00  1.35887962e+00  7.23742111e+00
  3.72721037e+00 -5.95852929e+00 -8.14618196e+00  6.77634077e-01
  5.79574684e+00 -6.26683353e-01  2.86191013e-01 -2.00362177e+00
  4.25735952e+00 -1.01064839e+00 -9.78454817e-03 -2.91250013e-01
 -3.62284384e+00 -3.52460385e+00  6.66913156e+00 -1.56071639e+00
  1.20756046e+01  2.15237560e+00 -2.65558024e+00 -8.95940671e+00
 -6.06650934e-01 -3.51058169e+00 -7.92355276e+00  5.62892331e+00
 -1.12789579e+01 -8.20676456e+00 -6.75810553e+00  2.62925270e+00
  8.24305241e-01 -1.31208301e+01  7.80103854e-01 -5.08349464e+00
 -2.15241667e+00 -3.27605299e+00  2.62698742e+00 -3.07873453e+00
 -4.67677819e+00  6.40982340e+00  8.70731580e+00 -3.64326366e+00
  6.06390106e+00  5.73205667e+00 -1.98500913e+00 -7.69761965e+00
 -5.81381251e+00 -5.31126563e+00 -3.47091442e-01 -1.53643788e+00
  4.97770833e-01 -1.81192357e+00  9.03287875e-01  6.50781954e+00
 -8.57498049e+00  1.32997413e+00 -1.33242001e+01 -3.92782425e+00
 -2.09362442e+00  3.31441095e+00 -3.98979197e+00  1.37677325e+00
  3.00198864e+00 -3.12009572e+00  1.49701730e+01  1.95900918e+01
  9.64841495e+00  7.90367283e+00  6.27642261e+00 -3.21690214e+00
  5.87244403e+00 -3.47834800e+00  2.78417539e+00 -5.83072778e+00
 -7.77537941e+00  2.48198667e+00  1.89913282e+00  1.49449204e+01
 -1.23398867e+00 -1.07161900e+01  4.69139788e+00 -8.53151260e+00
 -3.69808902e+00 -9.51824875e+00  3.20798888e+00  9.84012804e+00
  9.86377392e-02 -2.90037037e+00  6.80793412e+00  2.55171415e-01
 -1.10113884e+01 -6.68052166e-01  7.68940487e-01  5.55350998e+00
  2.15688608e+00 -7.95496631e+00  3.53838438e+00 -1.44384798e-01
  3.39720599e+00  3.17542331e+00  4.69352419e+00 -1.19889005e+01
 -1.13455146e+00 -6.41149850e+00 -2.93081077e-01 -6.66005943e+00
 -1.13708754e+01  4.56016868e+00 -1.31030002e+01  2.76528360e-01
  9.10114948e+00  4.35994410e+00 -1.73801857e+00 -4.88407321e+00
 -2.03615640e+01 -6.85002874e+00  7.60583362e+00  3.03904938e+00
  4.55607845e+00  4.51126086e+00  5.14507039e+00 -1.69194918e+00
 -8.46532929e+00 -5.31369992e+00  7.31369360e-01  2.47903157e+00
  7.83096545e+00 -3.95553784e+00 -2.75917967e+00 -5.38786164e+00
 -4.80323849e-01 -2.01262717e+00  4.23739785e+00  3.70923471e+00
  8.78953603e+00  8.15569882e+00  1.48420299e+01 -1.32272108e+00
 -1.40822240e+00 -3.22016661e+00 -5.52105834e+00 -4.96336636e+00
 -2.24689069e+00  5.00906538e+00 -4.56269652e+00  2.39979536e+00
 -2.03406552e+00 -1.76864335e+00 -2.54704938e+00 -5.51893619e-02
 -2.29514865e+00 -5.45242948e-01 -8.13229223e+00 -2.99809803e+00
 -4.73067939e+00  7.34846067e+00 -4.74543174e+00 -3.15674972e+00
  5.60536845e+00 -3.88169327e+00  8.62313705e+00  9.36252367e-01
 -1.02136190e+01 -2.64268593e+00 -1.13371293e+01  3.56367068e+00
 -6.77159525e+00  7.15817974e+00 -4.76017843e+00 -4.58604740e+00
  2.16914588e+00  5.60892510e+00  8.92690763e-01  5.59939289e+00
 -7.29873613e+00 -1.44693015e-01  1.01084431e+00  1.85047964e+00
  1.00471950e+01 -1.76634022e+00  8.45824453e-01 -9.04460887e+00
  3.50693216e+00 -8.75288136e+00  5.19374695e+00  4.62519772e+00
  1.23845107e+01  7.03500997e+00 -7.66844811e-01 -4.70291487e+00
  7.53559923e+00  3.45882003e+00 -2.18505041e+00 -4.64852896e+00
  8.79711730e-02 -3.02979000e+00  5.00050302e-01  1.07873272e+00
  6.61010373e+00 -1.99449837e+00  2.50637926e+00  6.91334419e+00
  4.43192984e-01  4.75347343e+00 -2.27773805e+00 -3.18369469e+00
 -1.18399378e+01  5.28628889e+00  5.13919154e-01  9.13137522e+00
 -1.06688079e+01 -8.19196148e+00  9.40310729e+00 -1.14333610e+00
  5.14922185e+00 -6.70674310e+00  8.18280188e+00 -2.21930296e+00
  3.89065158e+00 -3.06998575e+00 -3.35047712e+00 -2.43176353e-01
  4.03381012e+00  4.62823576e+00 -2.84633955e+00  4.80927349e+00
  2.16406023e+00  1.37939940e+00  1.26884569e+01 -3.73911717e-01
  7.03197012e+00  1.04319735e+01 -1.52711591e+00  5.96834347e+00
 -2.57413331e+00 -5.38405187e+00 -7.10994224e+00 -5.37398518e+00
 -6.83206934e+00 -1.08299204e+01  7.18480135e+00  3.66959046e+00
  1.00194066e+01  3.42287342e+00  1.32680195e+01 -1.17061609e+00
  2.33868109e+00 -9.96725581e+00 -8.56004012e+00 -5.83945426e+00
  7.81754649e+00 -7.84713158e+00 -5.71602345e+00  5.26009055e+00
  4.61827980e+00 -5.98573635e+00 -2.49245065e+00  6.42621706e+00
 -1.05778667e+01  6.32114132e+00 -1.71881375e+00  1.21227553e+00
  7.38215001e+00 -4.06621914e+00  3.00776753e+00  6.12307809e+00
  5.12476063e+00 -1.05352208e+00  2.08365253e+00 -1.08908496e+01
 -4.66837767e+00  4.47826737e+00  8.35124820e+00  9.42512979e+00
 -2.21598774e+00 -4.44956908e+00  1.27033918e+00 -1.59111423e-01
  1.02786974e+01  3.57458523e+00 -3.46572875e+00 -4.79462126e+00]

In [ ]:
print(f"Sample mean of U is {U.mean().round(3)} ")

Sample mean of U is -0.413

In [ ]:
print(f"Sample standard deviation of U is {U.std(ddof=1).round(3)}")

Sample standard deviation of U is 6.032

<p id="regression"><b>8.C</b></p>
Now generate the $y_i$ as $$y_i = 1+2x_i + u_i = \beta_0 + \beta_1x_i + u_i;$$ that is, the population intercept is one and the population slope is two. Use the data to run the regression of $y_i$ on $x_i$. What are your estimates of the intercept and slope? Are they equal to the population values in the above equation? Explain.

In [ ]:
2*X

array([1.11181084e+01, 1.92999114e+01, 1.39551220e+01, 1.03918079e+01,
       8.26823350e+00, 7.26841717e+00, 1.84456039e+01, 1.88101654e+01,
       6.54386844e-01, 1.81001770e+01, 8.71784539e+00, 1.91404958e+01,
       7.16692813e+00, 1.52197502e+01, 1.47589567e+01, 1.39573867e+01,
       4.99339283e+00, 3.61875052e+00, 1.11258418e+01, 3.73081622e+00,
       1.51436194e+00, 8.57300193e+00, 1.87383590e+01, 1.71550926e+01,
       1.11832573e+00, 4.38570072e+00, 7.55635295e+00, 1.00623438e+01,
       5.60423183e+00, 2.67687106e+00, 1.24120169e+01, 1.05577608e+01,
       2.10682637e+00, 6.74755625e-01, 2.43423903e+00, 8.17612588e+00,
       2.30313323e+00, 1.82214410e+01, 9.37366216e+00, 2.64728347e+00,
       1.50631479e+00, 8.19083720e+00, 1.50054173e+01, 1.89024625e+01,
       9.16382271e+00, 7.12667259e+00, 1.24124193e+01, 1.70022629e+01,
       9.90134784e+00, 1.98508862e+01, 5.89089564e+00, 1.42183846e-01,
       9.39513825e+00, 1.13452525e+01, 1.24610551e+01, 1.19414049e+01,
       9.62492021e+00, 1.89040487e+01, 4.08013909e+00, 1.55373730e+01,
       6.80457064e+00, 1.09624058e+00, 9.10810524e+00, 4.50677326e+00,
       1.52720681e+01, 7.74340588e+00, 1.64899032e+01, 7.47790160e-01,
       1.10596818e+01, 1.82997414e+01, 6.37955129e+00, 1.74937345e+01,
       7.44066886e+00, 8.19524815e-01, 4.68747469e+00, 2.16339411e+00,
       1.38760456e+01, 7.17818869e+00, 1.11447549e+01, 8.00090107e+00,
       1.53866799e+01, 1.25221948e+01, 8.03800978e+00, 6.74274327e+00,
       4.55025428e+00, 4.15392793e+00, 1.84334517e+01, 9.86375319e+00,
       3.26424158e+00, 7.07762843e+00, 1.73299678e+01, 3.30142596e-02,
       7.71229432e+00, 4.92844629e+00, 9.30674891e+00, 5.00440610e+00,
       9.75329596e+00, 1.44476052e+01, 6.46764036e+00, 1.21450971e+01,
       9.31991232e+00, 2.58998981e+00, 2.34692791e+00, 1.23503302e+01,
       1.35246615e+01, 1.66825989e+01, 7.40680354e+00, 8.81440873e+00,
       4.56841097e+00, 5.20731634e+00, 5.75411485e+00, 1.26326099e+01,
       1.12539984e+01, 8.63700657e+00, 7.16111499e+00, 5.07949072e+00,
       8.11081626e+00, 2.78753379e+00, 1.29885299e+01, 1.40011003e+01,
       7.37230481e+00, 6.99256848e+00, 1.22825736e+01, 1.03288607e+01,
       8.20465271e+00, 2.83019703e+00, 1.35114494e+01, 1.78701441e+01,
       1.84408833e+01, 5.86709978e+00, 4.13070451e+00, 5.90745820e+00,
       1.30736981e+01, 7.55770247e+00, 1.19623654e+01, 8.99226229e+00,
       3.03454331e+00, 1.62560031e+01, 3.92565217e+00, 2.55409037e+00,
       1.50667425e+01, 1.95171675e+01, 1.06619734e+01, 7.97144282e+00,
       7.09032016e+00, 1.07033811e+01, 2.30789274e+00, 1.13842442e+00,
       1.18573061e+01, 5.21654272e+00, 2.18769997e+00, 7.75607510e+00,
       1.55100169e+01, 4.33501149e-01, 1.29247946e+01, 1.26002756e+01,
       1.83600684e+01, 4.18684326e-01, 1.94736068e+01, 1.21446352e+00,
       6.08601724e+00, 2.02995507e+00, 1.56422857e+00, 1.96792588e+01,
       1.12871775e+00, 1.69938992e+00, 8.49723755e+00, 1.30667160e+01,
       5.68883593e+00, 1.38176652e+01, 1.58108901e+01, 1.17514266e+01,
       1.45017060e+01, 1.11151612e+01, 4.74632790e+00, 4.95181556e+00,
       1.54580137e+01, 1.52226290e+01, 3.80057995e+00, 1.30989980e+01,
       1.06154284e+01, 8.02338152e+00, 4.52958052e+00, 1.03948354e+01,
       1.68527719e+01, 7.32656103e+00, 3.39929538e+00, 4.08227282e+00,
       1.47727083e+01, 1.28024640e+01, 1.92741292e+01, 3.22192892e+00,
       9.01614281e+00, 3.50533817e+00, 1.83941126e+01, 1.97625819e+01,
       1.83333686e+01, 1.50922613e+01, 1.55551751e+01, 5.40627789e+00,
       1.06266117e+01, 7.28757292e+00, 1.95358663e-02, 6.37756081e-01,
       9.19038919e+00, 1.34259574e+01, 1.17214356e+01, 5.50787690e+00,
       9.08207802e+00, 1.66565647e+01, 1.00204949e+01, 1.67759726e+01,
       4.97389311e+00, 1.21288394e+01, 3.48527250e+00, 1.64772970e+00,
       1.46617299e+01, 5.86916849e+00, 2.43799086e+00, 1.19220120e+01,
       9.57593525e+00, 2.19189389e-01, 4.14092026e+00, 1.79669891e+00,
       1.82108644e+01, 9.84797541e+00, 7.71645529e+00, 4.70628366e+00,
       1.25188179e+01, 1.03654689e+01, 1.69676867e+01, 7.57324280e+00,
       1.30639159e+00, 1.90967713e+01, 1.22538967e+00, 5.49172212e+00,
       2.86038222e+00, 1.58688347e+01, 1.72379532e+01, 1.32476864e+00,
       1.61659548e+01, 2.52424345e+00, 3.19294743e+00, 1.52793343e+01,
       7.17370357e+00, 9.63708245e+00, 8.80051755e+00, 1.91659233e+01,
       1.40605917e+00, 1.97427128e+00, 5.41194857e+00, 1.89182067e+01,
       1.19817290e+01, 9.63193682e+00, 1.32778591e+01, 1.05488083e+01,
       1.83741508e+01, 1.79030296e+01, 8.00967413e+00, 1.95189855e+00,
       4.28883873e+00, 1.74407019e+01, 6.30063159e+00, 1.23034540e+01,
       5.39612351e+00, 1.19299014e+01, 1.40621294e+01, 8.75295706e-01,
       1.48505519e+01, 1.12099735e+01, 5.03573661e+00, 1.28833511e+01,
       1.30747311e+01, 8.50525671e+00, 4.48372247e+00, 1.16063585e+01,
       6.30201356e+00, 1.75000570e+01, 1.58067282e+01, 6.79837376e+00,
       1.04488570e+01, 1.39202458e+01, 1.27499384e+01, 1.28997257e+01,
       1.81809693e+01, 6.87440644e+00, 1.07399663e+01, 1.68018674e+01,
       1.85259366e+01, 2.46414013e+00, 3.42928631e-01, 5.09081205e-01,
       4.07035018e+00, 1.53405878e+01, 3.67304219e-01, 1.96925354e+01,
       4.48822312e+00, 1.35593435e+01, 6.94018264e+00, 4.07900937e+00,
       1.52403591e+01, 1.82700896e+01, 1.24167059e+01, 1.78308862e+01,
       9.56068103e+00, 1.32943569e+01, 1.81906774e+01, 3.73458149e+00,
       1.31996972e+01, 1.92283972e+01, 6.37829031e+00, 1.08540023e+01,
       9.32919041e+00, 8.61488214e+00, 4.04491196e+00, 1.54212234e+00,
       1.53169659e+01, 1.34851243e+01, 5.81292716e+00, 1.59559645e+01,
       8.98394768e+00, 3.44280572e+00, 1.54046701e+01, 2.33179736e+00,
       5.80999248e+00, 1.20165308e+01, 7.37967406e+00, 1.66037493e-01,
       1.24365061e+01, 3.16634488e+00, 4.06336813e+00, 1.21905355e+01,
       4.53939872e-01, 1.90237796e+01, 1.68271070e+01, 1.82435905e+01,
       5.93231987e+00, 5.87379349e+00, 1.41372020e+01, 1.83270787e+01,
       3.88356431e+00, 1.29148484e+01, 1.39355595e+01, 1.79415517e+01,
       2.86752480e+00, 6.08400388e+00, 3.48713861e+00, 1.42581052e+00,
       1.98159782e+01, 1.77200662e+01, 7.90994425e+00, 1.31556347e+01,
       1.68046918e+01, 2.31800258e+00, 1.72108622e-01, 3.67197721e+00,
       1.26476099e+01, 1.97978797e+01, 1.22849481e+01, 1.53137313e+01,
       1.75502516e+01, 7.66983234e-02, 4.19686339e+00, 1.95096219e+01,
       1.55816200e+01, 7.36930119e-01, 7.75555825e+00, 7.86116568e+00,
       3.29538441e+00, 3.38022358e+00, 1.41586562e+01, 9.97574654e+00,
       5.48367374e+00, 1.37187511e+01, 1.82226293e+01, 1.88053238e+00,
       1.92906750e+01, 4.58294216e+00, 2.11297430e+00, 4.40470419e+00,
       1.30071579e+01, 1.73133551e+01, 5.25076834e+00, 1.86422775e+01,
       1.57589783e+01, 4.62108790e+00, 1.52588054e+01, 5.46340831e+00,
       1.42670564e+01, 9.19448989e+00, 8.48595870e+00, 4.05907664e+00,
       1.16452467e+01, 5.15185641e+00, 5.62936866e+00, 1.63404254e+01,
       1.08809519e+01, 1.48437423e+01, 1.49294982e+01, 1.81696896e+01,
       7.19292068e+00, 1.89097188e+01, 1.80965927e+01, 3.17214623e+00,
       1.92190155e+01, 9.59009003e+00, 3.36487055e+00, 1.93320178e+01,
       6.85339573e+00, 5.08994570e+00, 1.32482794e+01, 8.79412129e+00,
       9.56017127e+00, 9.00284270e+00, 1.08567029e+01, 1.14958216e+01,
       1.33806849e+01, 5.75566429e-01, 1.93116505e+01, 1.80912543e+01,
       1.11442411e+01, 1.05598388e+01, 4.14458730e-01, 6.53699626e-01,
       9.48112644e+00, 1.80042236e+01, 9.56794211e+00, 9.80837201e+00,
       1.47830966e+00, 1.27403086e+01, 1.51089371e+01, 1.58333367e+01,
       6.82908201e+00, 1.56323572e+01, 7.66915895e+00, 2.62865490e+00,
       1.09865724e+01, 1.76002439e+01, 2.57949006e+00, 4.14862804e+00,
       1.60456420e+01, 3.26038175e+00, 1.10454729e+01, 4.75034177e+00,
       1.50789717e+01, 1.07622633e+01, 1.63615000e+01, 7.41865904e+00,
       1.28660040e+01, 1.70354680e+01, 3.82639384e+00, 6.62920273e+00,
       1.42965657e+01, 1.24140729e+01, 1.38133526e+01, 1.80026838e+01,
       8.29649380e+00, 1.96793258e+01, 2.62648373e+00, 1.13953147e+01,
       1.68491620e+01, 6.51712728e+00, 7.10470650e-02, 7.58825167e+00,
       7.08231155e+00, 6.16538846e+00, 1.88026268e+01, 2.56747059e+00,
       1.36849077e+01, 1.48377362e+01, 9.25149728e+00, 7.01897005e+00,
       6.05588368e+00, 1.45559652e+01, 1.96364616e+01, 7.79834790e-01,
       1.45458573e+01, 1.67414368e+01, 1.39369688e+01, 4.64876386e+00,
       3.87889555e+00, 1.63562131e+01, 4.25951269e+00, 1.28526116e+01,
       2.78878984e+00, 1.87415484e+01, 1.13393660e+01, 1.65076367e+01,
       1.77122090e+01, 4.67457005e+00, 8.67832455e+00, 3.89327011e-01,
       9.95186508e+00, 1.03424401e+01, 5.75277650e+00, 1.26530601e+01,
       8.54847709e+00, 1.29781169e+01, 9.13410745e+00, 1.22698736e+01])

In [ ]:
len(np.full((500),1))

500

In [ ]:
Y = np.full((500),1) + 2*X + U
print(f'Generate \n {Y}')

Generate
 [ 7.81788252e+00  1.78529178e+01  1.89924355e+01  2.96390999e+00
  5.71699945e-01  7.77983056e+00  1.50439619e+01  2.54605021e+01
 -7.07514047e+00  2.03966114e+01  3.74090834e+00  1.86624832e+01
  4.56136661e+00  1.25582902e+01  2.38893382e+01  1.74681813e+01
  4.78474317e+00  2.64984866e+00  1.43942389e+01  8.34810605e+00
 -6.26902316e+00  1.25794610e+01  1.48205798e+01  1.87565409e+01
 -4.55466679e+00 -5.88992910e-01  1.03389274e+01  3.61250675e+00
  9.57933766e+00  2.21617787e+00  1.55417090e+01  1.36197993e+01
 -4.59035757e+00 -6.19682607e+00 -2.73937496e+00  1.60935368e+01
 -6.94694606e+00  2.85296789e+01  1.29713139e+01 -1.83629951e+00
  1.94654678e+00  7.62712261e+00  1.66581075e+01  2.07230078e+01
  3.08442577e+00  9.35945641e+00  1.08907966e+01  7.47333463e+00
  4.20807060e+00  3.00438362e+01  5.85119261e+00 -8.70078072e+00
  1.74215273e+01  1.83864919e+01  9.08387410e+00  1.74793085e+01
  1.21440897e+01  2.01795870e+01  4.46546490e+00  2.00914973e+01
  1.12040069e+01 -1.60334474e+00  8.19726007e+00  4.38073587e+00
  1.59724973e+01  4.22684059e+00  1.87357607e+01 -4.99638652e-01
  1.26906818e+01  2.09569048e+01  1.43980853e+00  1.93618683e+01
 -2.55768145e+00 -3.94708178e+00  9.15585749e+00  6.05625923e+00
  1.32290966e+01 -7.04240939e-01  1.45983452e+01  1.38165913e+00
  1.27601770e+01  1.63176287e+01  1.17645984e+01 -2.37414505e+00
 -3.75717797e+00  3.78986086e+00  1.69622444e+01  1.75360020e+01
 -2.59702050e+00  1.35119876e+01  1.78357510e+01 -4.14884946e+00
  1.20466381e+01  6.88379820e-01  8.04907897e+00  1.08156426e+00
  1.18002413e+01  6.73320977e+00  1.51386901e+01  1.18059108e+01
  1.48439745e+01 -5.68862027e+00 -3.74606680e+00  1.31556027e+01
  1.63017810e+01  4.90084862e+00 -4.31922385e+00  1.69584955e+01
  7.64666315e+00  1.52411991e+01 -9.02764294e-01  2.18742979e+01
  1.37439910e+00  1.84183970e+01  2.28072220e+01  5.35155375e+00
  1.20091986e+01  4.49160111e+00  1.56903763e+01  1.58057938e+01
  1.36127569e+01  5.68853290e+00  1.65756214e+01  8.45575822e+00
  6.16345857e+00 -2.49659189e+00  1.32615843e+01  2.90150576e+01
  9.64355745e+00  1.64650785e+00  1.92017369e+01 -3.77321544e+00
 -2.53264625e+00  5.92246294e+00 -2.49605861e+00  7.15331624e+00
  3.99726299e+00  2.11957489e+01  8.81839916e+00  1.10715983e+01
  2.05943478e+01  1.72322057e+01  5.96814578e+00  6.06886885e+00
  1.25560532e+01  1.85648002e+01  8.04844609e+00  9.39375429e+00
  1.70581832e+01  3.47300975e+00  5.51643826e+00 -5.48240504e+00
  7.57126802e+00  1.08235800e+00  2.49336597e+01  3.58759948e+00
  2.42796679e+01  2.04304615e-01  2.86437319e+01 -1.08934573e+01
  6.31023670e-01  5.06556101e+00  2.99799643e+00  2.79662378e+01
  9.68367779e+00 -3.43276470e+00  7.98079226e+00  1.42390817e+01
  1.04649112e+01  1.24444118e+01  9.34942058e+00  9.94235422e+00
  1.50301197e+01  1.69122831e+01  7.88438659e+00  1.14118460e+01
  2.40460636e+01  1.77583001e+01  4.63284403e+00  2.04925781e+01
  1.09809400e+01  1.27565390e+01  1.75051733e+00  1.33653860e+01
  1.57875846e+01  2.37095919e+00 -3.47218400e+00  2.06508127e+01
  2.53349385e+01  8.10558712e+00  1.70954528e+01 -1.94384974e+00
  7.63283294e+00  1.07815933e+01  1.91152518e+01  2.18201278e+01
  1.25215908e+01  2.04337427e+01  1.59408345e+01  3.74653924e-01
  6.10431681e+00  5.04553802e+00 -3.27696078e+00 -2.54482982e+00
  6.28468568e+00  1.59200567e+01  1.21613477e+01 -6.36791652e+00
  1.18497753e+01  2.29518433e+01  1.57656438e+01  1.97292426e+01
  3.44877248e+00  1.25079414e+01 -3.61969063e+00  4.55969230e+00
  1.89729115e+01  3.79400869e+00  4.79687048e+00  2.01594331e+01
  1.43031456e+01 -4.73933990e+00 -3.00526170e+00  3.47433299e+00
  2.50066113e+01  1.02212921e+01  9.00264631e+00  3.70266190e+00
  1.77761774e+01  1.03548205e+01  1.79579022e+01  8.28199279e+00
 -1.31645226e+00  1.65721674e+01  8.89452123e+00  4.93100573e+00
  1.59359868e+01  1.90212103e+01  1.55823729e+01 -6.63463807e+00
  1.65593038e+01  1.36617594e-02 -3.73060533e+00  2.19082576e+01
 -3.10525438e+00  2.43031789e+00  3.04241202e+00  2.27951760e+01
  3.23036441e+00 -1.01465588e+01  7.19205243e+00  1.48347120e+01
  1.08293124e+01  7.35588383e+00  1.69048465e+01  8.47007377e+00
  1.46973726e+01  2.53128530e+01  1.77169899e+01 -6.91365119e-01
  1.13527398e+01  2.41727586e+01  5.31562246e+00  5.60583435e+00
  5.82311005e-01  7.61863581e+00  1.47150380e+01  3.38857829e-01
  1.63483227e+01  1.03980500e+01  6.93902449e+00  2.03911707e+01
  5.49975060e+00  1.08352308e+01 -7.84047768e+00  8.67853420e+00
  5.20838913e+00  2.18144679e+01  1.28169363e+01  9.17514701e+00
  1.44508456e+01  1.18001500e+01  2.87201113e+01  3.34898174e+01
  2.88293842e+01  1.57780793e+01  1.80163889e+01  1.45849652e+01
  2.53983806e+01 -1.42078706e-02  4.12710402e+00 -4.32164658e+00
 -2.70502924e+00  1.88225745e+01  3.26643703e+00  3.56374558e+01
  4.25423445e+00  3.84315342e+00  1.26315805e+01 -3.45250323e+00
  1.25422701e+01  9.75184089e+00  1.66246948e+01  2.86710142e+01
  1.06593188e+01  1.13939865e+01  2.59986116e+01  4.98975291e+00
  3.18830880e+00  1.95603451e+01  8.14723080e+00  1.74075123e+01
  1.24860765e+01  1.65991583e+00  8.58329635e+00  2.39773754e+00
  1.97141719e+01  1.76605476e+01  1.15064513e+01  4.96706401e+00
  8.84939623e+00 -1.96869278e+00  1.61115891e+01 -3.32826207e+00
 -4.56088290e+00  1.75766995e+01 -4.72332616e+00  1.44256585e+00
  2.25376556e+01  8.52628898e+00  3.32534956e+00  8.30646229e+00
 -1.89076242e+01  1.31737508e+01  2.54329406e+01  2.22826399e+01
  1.14883983e+01  1.13850544e+01  2.02822724e+01  1.76351295e+01
 -3.58176498e+00  8.60114852e+00  1.56669289e+01  2.14205833e+01
  1.16984902e+01  3.12846605e+00  1.72795894e+00 -2.96205113e+00
  2.03356543e+01  1.67074390e+01  1.31473421e+01  1.78648694e+01
  2.65942278e+01  1.14737014e+01  1.60141386e+01  3.34925613e+00
  1.22393875e+01  1.75777131e+01  7.76388972e+00  1.13503649e+01
  1.63033610e+01  6.08576370e+00  6.34166871e-01  2.29094173e+01
  1.45475545e+01 -3.17132273e-02  6.20850887e+00  8.80597632e+00
  2.00023576e+00  3.83498063e+00  7.02636394e+00  7.97764851e+00
  1.75299435e+00  2.20672118e+01  1.44771975e+01 -2.76217338e-01
  2.58960435e+01  1.70124888e+00  1.17361113e+01  6.34095656e+00
  3.79353886e+00  1.56706692e+01 -5.08636098e+00  2.32059482e+01
  9.98738305e+00  1.27792676e+01  1.14986269e+01  1.87736090e+00
  1.74362023e+01  1.58034150e+01  1.03786495e+01  1.06584695e+01
  5.34651056e+00  6.00716339e+00  7.64021297e+00  1.91909051e+01
  2.19281469e+01  1.40774020e+01  1.67753227e+01  1.01250807e+01
  1.16998528e+01  1.11568374e+01  2.42903397e+01  8.79734396e+00
  3.26035262e+01  1.76251000e+01  3.59802574e+00  1.56291029e+01
  1.53889950e+01  9.54876574e+00  1.20632290e+01  5.14559233e+00
  1.06481424e+01  6.97305270e+00  1.23567532e+01  1.35745543e+01
  2.09907887e+01 -4.18931942e-01  2.28180298e+01  2.60045985e+01
  1.25874341e+01  1.63133123e+01 -8.63279316e-01 -1.52999506e+00
 -1.35881133e+00  2.42905125e+01  1.10818613e+01  1.99397472e+01
 -8.19049822e+00  5.54834716e+00  2.55120444e+01  1.56900006e+01
  1.29783039e+01  9.92561407e+00  1.68519608e+01  1.40935195e+00
  1.58772240e+01  1.55302581e+01  2.29012940e-01  4.90545168e+00
  2.10794521e+01  8.88861752e+00  9.19913334e+00  1.05596153e+01
  1.82430320e+01  1.31416627e+01  3.00499569e+01  8.04474732e+00
  2.08979741e+01  2.84674415e+01  3.29927793e+00  1.35975462e+01
  1.27224324e+01  8.03002106e+00  7.70341035e+00  1.36286987e+01
  2.46442446e+00  9.84940538e+00  1.08112851e+01  1.60649051e+01
  2.78685686e+01  1.09400007e+01  1.43390666e+01  7.41763558e+00
  1.04209926e+01 -2.80186734e+00  1.12425867e+01 -2.27198367e+00
  2.25024542e+01  7.99060466e+00  4.53547383e+00  1.32790606e+01
  1.16741635e+01  9.57022890e+00  1.81440109e+01  8.20605185e+00
  4.96799062e+00  2.40625781e+01  1.32181550e+01  6.86103939e+00
  1.22610456e+01  1.32899940e+01  8.26728023e+00  1.99756897e+01
  8.91355046e+00  1.86880263e+01  1.44230185e+01  6.61678703e+00
  1.40438313e+01  1.01528374e+01  1.80295728e+01  1.08144568e+01
  8.73587734e+00  6.89287103e+00  8.02311568e+00  1.34939486e+01
  1.98271745e+01  1.75527022e+01  6.66837869e+00  8.47525237e+00]

In [ ]:
import statsmodels.api as sm # Library for getting model from np.array()
X = sm.add_constant(X) # add intercept of model
model = sm.OLS(Y,X) # creating models
res = model.fit() # fitting()
print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.525
Model:                            OLS   Adj. R-squared:                  0.524
Method:                 Least Squares   F-statistic:                     550.7
Date:                Tue, 22 Sep 2026   Prob (F-statistic):           1.43e-82
Time:                        14:58:45   Log-Likelihood:                -1605.0
No. Observations:                 500   AIC:                             3214.
Df Residuals:                     498   BIC:                             3222.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.4341      0.532     -0.817      0.414      -1.479       0.610
x1             2.2097      0.094     23.468      0.000       2.025       2.395
==============================================================================
Omnibus:                        0.058   Durbin-Watson:                   1.882
Prob(Omnibus):                  0.971   Jarque-Bera (JB):                0.091
Skew:                           0.026   Prob(JB):                        0.956
Kurtosis:                       2.958   Cond. No.                         11.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
print(f'The estimate of intercept is  {res.params[0].round(3)}')

The estimate of intercept is  -0.434

In [ ]:
print(f'The estimate of slope is  {res.params[1].round(3)}')

The estimate of slope is  2.21

<p id="quantities"><b>8.D</b></p>
 Compute the same [quantities](#quantities) in equation $$\sum\limits_{i=1}^n \hat{u}_i = 0, \sum\limits_{i=1}^n x_i\hat{u}_i = 0  $$ but use the errors $u_i$ in place of the residuals. Now what do you conclude?

In [ ]:
print(f"Sum of residuals is {res.resid.sum().round(10)}")

Sum of residuals is 0.0

In [ ]:
print(f"Sum of x*residuals is {(X[:,1]*res.resid).sum().round(5)}")

Sum of x*residuals is 0.0

In [ ]:
print(f"Sum of errors u is {U.sum().round(3)}")
print(f"Sum of x*u is {(X[:,1]*U).sum().round(3)}")

Sum of errors u is -206.259
Sum of x*u is -150.808