In [1]:
import numpy as np
import matplotlib.pyplot as plt
import wooldridge
from statsmodels.iolib.summary2 import summary_col

In [2]:
wooldridge.data()

  J.M. Wooldridge (2019) Introductory Econometrics: A Modern Approach,
  Cengage Learning, 6th edition.

  401k       401ksubs    admnrev       affairs     airfare
  alcohol    apple       approval      athlet1     athlet2
  attend     audit       barium        beauty      benefits
  beveridge  big9salary  bwght         bwght2      campus
  card       catholic    cement        census2000  ceosal1
  ceosal2    charity     consump       corn        countymurders
  cps78_85   cps91       crime1        crime2      crime3
  crime4     discrim     driving       earns       econmath
  elem94_95  engin       expendshares  ezanders    ezunem
  fair       fertil1     fertil2       fertil3     fish
  fringe     gpa1        gpa2          gpa3        happiness
  hprice1    hprice2     hprice3       hseinv      htv
  infmrt     injury      intdef        intqrt      inven
  jtrain     jtrain2     jtrain3       kielmc      lawsch85
  loanapp    lowbrth     mathpnl       meap00_01   meap01
  meap93     meapsingle  minwage       mlb1        mroz
  murder     nbasal      nyse          okun        openness
  pension    phillips    pntsprd       prison      prminwge
  rdchem     rdtelec     recid         rental      return
  saving     sleep75     slp75_81      smoke       traffic1
  traffic2   twoyear     volat         vote1       vote2
  voucher    wage1       wage2         wagepan     wageprc
  wine

In [3]:
wooldridge.data('airfare', description=True)

name of dataset: airfare
no of variables: 14
no of observations: 4596

+----------+----------------------------------+
| variable | label                            |
+----------+----------------------------------+
| year     | 1997, 1998, 1999, 2000           |
| id       | route identifier                 |
| dist     | distance, in miles               |
| passen   | avg. passengers per day          |
| fare     | avg. one-way fare, $             |
| bmktshr  | fraction market, biggest carrier |
| ldist    | log(distance)                    |
| y98      | =1 if year == 1998               |
| y99      | =1 if year == 1999               |
| y00      | =1 if year == 2000               |
| lfare    | log(fare)                        |
| ldistsq  | ldist^2                          |
| concen   | = bmktshr                        |
| lpassen  | log(passen)                      |
+----------+----------------------------------+

Jiyoung Kwon, a former doctoral student in economics at MSU, kindly
provided these data, which she obtained from the Domestic Airline
Fares Consumer Report by the U.S. Department of Transportation.

In [4]:
df = wooldridge.data('airfare')
df.loc[1:20]

,year,id,dist,passen,fare,bmktshr,ldist,y98,y99,y00,lfare,ldistsq,concen,lpassen
1,1998,1,528,265,106,0.8133,6.269096,1,0,0,4.663439,39.301571,0.8133,5.579730
2,1999,1,528,336,113,0.8262,6.269096,0,1,0,4.727388,39.301571,0.8262,5.817111
3,2000,1,528,298,123,0.8612,6.269096,0,0,1,4.812184,39.301571,0.8612,5.697093
4,1997,2,861,282,104,0.5798,6.758094,0,0,0,4.644391,45.671837,0.5798,5.641907
5,1998,2,861,178,105,0.5817,6.758094,1,0,0,4.653960,45.671837,0.5817,5.181784
6,1999,2,861,204,115,0.7319,6.758094,0,1,0,4.744932,45.671837,0.7319,5.318120
7,2000,2,861,190,129,0.5386,6.758094,0,0,1,4.859812,45.671837,0.5386,5.247024
8,1997,3,852,241,207,0.8180,6.747587,0,0,0,5.332719,45.529926,0.8180,5.484797
9,1998,3,852,253,188,0.8172,6.747587,1,0,0,5.236442,45.529926,0.8172,5.533390
10,1999,3,852,244,229,0.7998,6.747587,0,1,0,5.433722,45.529926,0.7998,5.497168
11,2000,3,852,244,247,0.7097,6.747587,0,0,1,5.509388,45.529926,0.7097,5.497168
12,1997,4,724,233,243,0.4604,6.584791,0,0,0,5.493062,43.359474,0.4604,5.451038
13,1998,4,724,248,226,0.4614,6.584791,1,0,0,5.420535,43.359474,0.4614,5.513429
14,1999,4,724,224,229,0.4334,6.584791,0,1,0,5.433722,43.359474,0.4334,5.411646
15,2000,4,724,339,176,0.3716,6.584791,0,0,1,5.170484,43.359474,0.3716,5.826000
16,1997,5,1073,396,119,0.4571,6.978214,0,0,0,4.779123,48.695469,0.4571,5.981414
17,1998,5,1073,529,105,0.5632,6.978214,1,0,0,4.653960,48.695469,0.5632,6.270988
18,1999,5,1073,494,121,0.5008,6.978214,0,1,0,4.795791,48.695469,0.5008,6.202536
19,2000,5,1073,710,109,0.5197,6.978214,0,0,1,4.691348,48.695469,0.5197,6.565265
20,1997,6,318,237,181,0.9100,5.762052,0,0,0,5.198497,33.201237,0.9100,5.468060

In [5]:
len(df['year'])

4596

In [6]:
sum(df['year'])

9185106

In [7]:
sum(df.loc[1:20]['year'])

39970

In [8]:
sum(df.loc[1:20]['gnews'])

KeyError: 'gnews'

In [9]:
import statsmodels.formula.api as smf
mod = smf.ols(formula='year ~ gnews', data=df.loc[1:20])
res = mod.fit()
print(res.summary())

PatsyError: Error evaluating factor: NameError: name 'gnews' is not defined
    year ~ gnews
           ^^^^^

In [ ]:
res.ssr

In [ ]:
df.loc[1:10].describe()

In [ ]:
df = wooldridge.data('bwght')
df.loc[1:10].describe()

In [ ]:
import statsmodels.api as sm

In [ ]:
import random

print(random.randint(3, 9))

In [ ]:
x = [random.randint(1, 3) for _ in range(10)]
print(x, sum(x))

In [ ]:
y = [random.randint(3, 7) for _ in range(10)]
print(x, sum(y))

In [ ]:
x

In [ ]:
x = [random.randint(1, 5) for _ in range(10)]
y = [random.randint(3, 8) for _ in range(10)]
print(x, y)

In [ ]:
x = [random.randint(5, 10) for _ in range(10)]
y = [random.randint(10, 20) for _ in range(10)]
x2 = [i**2 for i in x]
y2 = [i**2 for i in y]
X = sm.add_constant(x)
res_ols = sm.OLS(y, X).fit()
print(f"sum:{sum(x)}, sumY:{sum(y)}, sum(X*Y):{sum(np.multiply(x,y))}, sumX**2:{sum(x2)}, sumY**2:{sum(y2)}, beta:{res_ols.params[1].round(2)} ")

In [ ]:
print(res_ols.summary())

In [10]:
 wooldridge.data('alcohol', description=True)

name of dataset: alcohol
no of variables: 33
no of observations: 9822

+------------+----------------------------------------------------+
| variable   | label                                              |
+------------+----------------------------------------------------+
| abuse      | =1 if abuse alcohol                                |
| status     | out of workforce = 1; unemployed = 2, employed = 3 |
| unemrate   | state unemployment rate                            |
| age        | age in years                                       |
| educ       | years of schooling                                 |
| married    | =1 if married                                      |
| famsize    | family size                                        |
| white      | =1 if white                                        |
| exhealth   | =1 if in excellent health                          |
| vghealth   | =1 if in very good health                          |
| goodhealth | =1 if in good health                               |
| fairhealth | =1 if in fair health                               |
| northeast  | =1 if live in northeast                            |
| midwest    | =1 if live in midwest                              |
| south      | =1 if live in south                                |
| centcity   | =1 if live in central city of MSA                  |
| outercity  | =1 if in outer city of MSA                         |
| qrt1       | =1 if interviewed in first quarter                 |
| qrt2       | =1 if interviewed in second quarter                |
| qrt3       | =1 if interviewed in third quarter                 |
| beertax    | state excise tax, $ per gallon                     |
| cigtax     | state cigarette tax, cents per pack                |
| ethanol    | state per-capita ethanol consumption               |
| mothalc    | =1 if mother an alcoholic                          |
| fathalc    | =1 if father an alcoholic                          |
| livealc    | =1 if lived with alcoholic                         |
| inwf       | =1 if status > 1                                   |
| employ     | =1 if employed                                     |
| agesq      | age^2                                              |
| beertaxsq  | beertax^2                                          |
| cigtaxsq   | cigtax^2                                           |
| ethanolsq  | ethanol^2                                          |
| educsq     | educ^2                                             |
+------------+----------------------------------------------------+

Terza, J.V. (2002), “Alcohol Abuse and Employment: A Second Look,”
Journal of Applied Econometrics 17, 393-404. I obtained these data
from the Journal of Applied Econometrics data archive at
http://qed.econ.queensu.ca/jae/.

In [11]:
alcohol = wooldridge.data('alcohol')
alcohol

,abuse,status,unemrate,age,educ,married,famsize,white,exhealth,vghealth,...,mothalc,fathalc,livealc,inwf,employ,agesq,beertaxsq,cigtaxsq,ethanolsq,educsq
0,1,1,4.0,50,4,1,1,1,0,0,...,0,0,0,0,0,2500,0.111556,1444.0,4.159397,16
1,0,3,4.0,37,12,1,5,1,0,0,...,0,0,0,1,1,1369,0.111556,1444.0,4.159397,144
2,0,3,4.0,53,9,1,3,1,1,0,...,0,0,0,1,1,2809,0.111556,1444.0,4.159397,81
3,0,3,3.3,59,11,1,1,1,1,0,...,0,0,0,1,1,3481,0.057600,676.0,6.002402,121
4,0,3,3.3,43,10,1,1,1,1,0,...,0,1,1,1,1,1849,0.057600,676.0,6.002402,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9817,0,3,6.7,43,12,0,4,1,0,1,...,0,0,0,1,1,1849,0.822649,529.0,1.916508,144
9818,0,3,6.7,38,13,1,5,1,1,0,...,0,0,0,1,1,1444,0.822649,529.0,1.916508,169
9819,0,3,6.7,40,13,1,6,1,0,1,...,0,0,0,1,1,1600,0.822649,529.0,1.916508,169
9820,0,3,6.7,29,11,0,2,0,0,1,...,0,0,0,1,1,841,0.822649,529.0,1.916508,121
9821,0,3,7.7,30,12,1,2,1,1,0,...,0,0,0,1,1,900,0.202500,441.0,1.833208,144

In [12]:
alchl = smf.ols(formula = "beertaxsq ~ cigtaxsq", data=alcohol).fit()
print(alchl.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              beertaxsq   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                  0.001
Method:                 Least Squares   F-statistic:                     11.93
Date:                Sun, 14 Sep 2025   Prob (F-statistic):           0.000554
Time:                        21:55:21   Log-Likelihood:                -12804.
No. Observations:                9822   AIC:                         2.561e+04
Df Residuals:                    9820   BIC:                         2.563e+04
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.4209      0.015     27.637      0.000       0.391       0.451
cigtaxsq      -0.0001   3.27e-05     -3.454      0.001      -0.000   -4.89e-05
==============================================================================
Omnibus:                     8400.310   Durbin-Watson:                   0.270
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           192152.994
Skew:                           4.206   Prob(JB):                         0.00
Kurtosis:                      22.969   Cond. No.                         788.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [13]:
econmath = wooldridge.data('campus')
model_trf = smf.ols(formula = "mathscr~study", data = econmath[1:18]).fit()
print(model_trf.summary())

PatsyError: Error evaluating factor: NameError: name 'study' is not defined
    mathscr~study
            ^^^^^

In [14]:
score = wooldridge.data('econmath')
model_trf = smf.ols(formula = "score~np.log(mathscr)", data = econmath[1:20]).fit()
print(model_trf.summary())

PatsyError: Error evaluating factor: NameError: name 'mathscr' is not defined
    score~np.log(mathscr)
          ^^^^^^^^^^^^^^^

In [15]:
wooldridge.data('campus', description =True)

name of dataset: campus
no of variables: 7
no of observations: 97

+----------+-----------------------+
| variable | label                 |
+----------+-----------------------+
| enroll   | total enrollment      |
| priv     | =1 if private college |
| police   | employed officers     |
| crime    | total campus crimes   |
| lcrime   | log(crime)            |
| lenroll  | log(enroll)           |
| lpolice  | log(police)           |
+----------+-----------------------+

These data were collected by Daniel Martin, a former MSU
undergraduate, for a final project. They come from the FBI Uniform
Crime Reports and are for the year 1992.

In [16]:
airfare = wooldridge.data('airfare')

In [17]:
model_1 = smf.ols(formula = "fare~np.log(dist)", data = airfare[1:25]).fit()
model_2 = smf.ols(formula = "np.log(fare)~np.log(dist)", data = airfare[1:25]).fit()
model_3 = smf.ols(formula = "np.log(fare)~dist", data = airfare[1:25]).fit()
model_4 = smf.ols(formula = "fare~dist", data = airfare[1:25]).fit()
print(summary_col([model_1, model_2, model_3,model_4],
                  stars=True,
                  model_names=["Модель 1", "Модель 2", "Модель 3", "Модель 3"]))

===========================================================
               Модель 1 I Модель 2 I Модель 3 I Модель 3 II
-----------------------------------------------------------
Intercept      291.1002*  6.0424***  5.2355***  188.8863***
               (166.4287) (1.0300)   (0.1976)   (31.8909)
R-squared      0.0260     0.0406     0.0426     0.0304
R-squared Adj. -0.0183    -0.0030    -0.0010    -0.0137
dist                                 -0.0002    -0.0330
                                     (0.0002)   (0.0398)
np.log(dist)   -19.4142   -0.1513
               (25.3456)  (0.1569)
===========================================================
Standard errors in parentheses.
* p<.1, ** p<.05, ***p<.01